package models

import (
	"time"
)

// OrderType represents the type of order
type OrderType string

const (
	Market     OrderType = "MARKET"
	Limit      OrderType = "LIMIT"
	StopLoss   OrderType = "STOP_LOSS"
	StopLimit  OrderType = "STOP_LIMIT"
	TakeProfit OrderType = "TAKE_PROFIT"
)

// OrderSide represents the side of the order (buy or sell)
type OrderSide string

const (
	Buy  OrderSide = "BUY"
	Sell OrderSide = "SELL"
)

// OrderStatus represents the status of an order
type OrderStatus string

const (
	Pending   OrderStatus = "PENDING"
	Submitted OrderStatus = "SUBMITTED"
	Filled    OrderStatus = "FILLED"
	Partial   OrderStatus = "PARTIAL"
	Cancelled OrderStatus = "CANCELLED"
	Rejected  OrderStatus = "REJECTED"
	Expired   OrderStatus = "EXPIRED"
)

// TradeStatus represents the status of a trade
type TradeStatus string

const (
	Open     TradeStatus = "OPEN"
	Closed   TradeStatus = "CLOSED"
	Canceled TradeStatus = "CANCELED"
)

// SignalType represents the type of trading signal
type SignalType string

const (
	Entry SignalType = "ENTRY"
	Exit  SignalType = "EXIT"
)

// SignalStrength represents the strength/confidence of a trading signal
type SignalStrength string

const (
	Strong  SignalStrength = "STRONG"
	Medium  SignalStrength = "MEDIUM"
	Weak    SignalStrength = "WEAK"
	Neutral SignalStrength = "NEUTRAL"
)

// Signal represents a trading signal generated by a strategy
type Signal struct {
	ID           uint          `json:"id" gorm:"primaryKey;autoIncrement"`
	Symbol       string        `json:"symbol" gorm:"type:varchar(20);index"`
	StrategyID   uint          `json:"strategy_id" gorm:"index"`
	Type         SignalType    `json:"type" gorm:"type:varchar(20);index"`
	Side         OrderSide     `json:"side" gorm:"type:varchar(10);index"`
	Price        float64       `json:"price" gorm:"type:decimal(10,2)"`
	Strength     SignalStrength `json:"strength" gorm:"type:varchar(20)"`
	Confidence   float64       `json:"confidence" gorm:"type:decimal(5,2)"` // 0.0 to 1.0
	Reason       string        `json:"reason" gorm:"type:text"`
	Indicators   string        `json:"indicators" gorm:"type:text"` // JSON string of indicator values
	IsProcessed  bool          `json:"is_processed" gorm:"default:false;index"`
	IsValid      bool          `json:"is_valid" gorm:"default:true;index"`
	GeneratedAt  time.Time     `json:"generated_at" gorm:"index"`
	ProcessedAt  *time.Time    `json:"processed_at"`
	CreatedAt    time.Time     `json:"created_at" gorm:"autoCreateTime"`
}

// Order represents a trading order
type Order struct {
	ID            uint        `json:"id" gorm:"primaryKey;autoIncrement"`
	TradeID       uint        `json:"trade_id" gorm:"index"`
	SignalID      *uint       `json:"signal_id" gorm:"index"`
	Symbol        string      `json:"symbol" gorm:"type:varchar(20);index"`
	Type          OrderType   `json:"type" gorm:"type:varchar(20);index"`
	Side          OrderSide   `json:"side" gorm:"type:varchar(10);index"`
	Quantity      float64     `json:"quantity" gorm:"type:decimal(10,4)"`
	Price         float64     `json:"price" gorm:"type:decimal(10,2)"`
	StopPrice     *float64    `json:"stop_price" gorm:"type:decimal(10,2)"`
	LimitPrice    *float64    `json:"limit_price" gorm:"type:decimal(10,2)"`
	FilledQty     float64     `json:"filled_qty" gorm:"type:decimal(10,4);default:0"`
	AvgFillPrice  *float64    `json:"avg_fill_price" gorm:"type:decimal(10,2)"`
	Status        OrderStatus `json:"status" gorm:"type:varchar(20);index"`
	ExternalID    string      `json:"external_id" gorm:"type:varchar(100);index"` // ID from broker
	ErrorMessage  string      `json:"error_message" gorm:"type:text"`
	SubmittedAt   *time.Time  `json:"submitted_at"`
	FilledAt      *time.Time  `json:"filled_at"`
	CancelledAt   *time.Time  `json:"cancelled_at"`
	CreatedAt     time.Time   `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt     time.Time   `json:"updated_at" gorm:"autoUpdateTime"`
}

// Trade represents a complete trade (entry and exit)
type Trade struct {
	ID              uint        `json:"id" gorm:"primaryKey;autoIncrement"`
	StrategyID      uint        `json:"strategy_id" gorm:"index"`
	Symbol          string      `json:"symbol" gorm:"type:varchar(20);index"`
	Side            OrderSide   `json:"side" gorm:"type:varchar(10);index"`
	EntryPrice      float64     `json:"entry_price" gorm:"type:decimal(10,2)"`
	ExitPrice       *float64    `json:"exit_price" gorm:"type:decimal(10,2)"`
	Quantity        float64     `json:"quantity" gorm:"type:decimal(10,4)"`
	ProfitLoss      *float64    `json:"profit_loss" gorm:"type:decimal(10,2)"`
	ProfitLossPct   *float64    `json:"profit_loss_pct" gorm:"type:decimal(10,2)"`
	Status          TradeStatus `json:"status" gorm:"type:varchar(20);index"`
	StopLoss        *float64    `json:"stop_loss" gorm:"type:decimal(10,2)"`
	TakeProfit      *float64    `json:"take_profit" gorm:"type:decimal(10,2)"`
	RiskRewardRatio *float64    `json:"risk_reward_ratio" gorm:"type:decimal(5,2)"`
	Notes           string      `json:"notes" gorm:"type:text"`
	EntrySignalID   *uint       `json:"entry_signal_id" gorm:"index"`
	ExitSignalID    *uint       `json:"exit_signal_id" gorm:"index"`
	EntryTime       time.Time   `json:"entry_time" gorm:"index"`
	ExitTime        *time.Time  `json:"exit_time"`
	CreatedAt       time.Time   `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt       time.Time   `json:"updated_at" gorm:"autoUpdateTime"`
}

// Strategy represents a trading strategy
type Strategy struct {
	ID               uint      `json:"id" gorm:"primaryKey;autoIncrement"`
	Name             string    `json:"name" gorm:"type:varchar(100);uniqueIndex"`
	Description      string    `json:"description" gorm:"type:text"`
	Type             string    `json:"type" gorm:"type:varchar(50)"` // e.g., "Trend Following", "Mean Reversion"
	Timeframe        string    `json:"timeframe" gorm:"type:varchar(20)"`
	Parameters       string    `json:"parameters" gorm:"type:text"` // JSON string of strategy parameters
	IsActive         bool      `json:"is_active" gorm:"default:true;index"`
	SuccessRate      float64   `json:"success_rate" gorm:"type:decimal(5,2);default:0"`
	AverageProfitPct float64   `json:"average_profit_pct" gorm:"type:decimal(5,2);default:0"`
	SharpRatio       float64   `json:"sharp_ratio" gorm:"type:decimal(5,2);default:0"`
	MaxDrawdown      float64   `json:"max_drawdown" gorm:"type:decimal(5,2);default:0"`
	CreatedAt        time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt        time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// RiskProfile represents risk management settings
type RiskProfile struct {
	ID                 uint      `json:"id" gorm:"primaryKey;autoIncrement"`
	Name               string    `json:"name" gorm:"type:varchar(100);uniqueIndex"`
	MaxPositionSize    float64   `json:"max_position_size" gorm:"type:decimal(10,2)"`
	MaxPositionPercent float64   `json:"max_position_percent" gorm:"type:decimal(5,2)"`
	MaxDrawdown        float64   `json:"max_drawdown" gorm:"type:decimal(5,2)"`
	RiskPerTrade       float64   `json:"risk_per_trade" gorm:"type:decimal(5,2)"`
	MinRiskRewardRatio float64   `json:"min_risk_reward_ratio" gorm:"type:decimal(5,2)"`
	IsDefault          bool      `json:"is_default" gorm:"default:false"`
	CreatedAt          time.Time `json:"created_at" gorm:"autoCreateTime"`
	UpdatedAt          time.Time `json:"updated_at" gorm:"autoUpdateTime"`
}

// PerformanceMetric represents trading performance metrics
type PerformanceMetric struct {
	ID                uint      `json:"id" gorm:"primaryKey;autoIncrement"`
	StrategyID        *uint     `json:"strategy_id" gorm:"index"`
	Symbol            *string   `json:"symbol" gorm:"type:varchar(20);index"`
	Period            string    `json:"period" gorm:"type:varchar(20);index"` // e.g., "daily", "weekly", "monthly"
	StartDate         time.Time `json:"start_date"`
	EndDate           time.Time `json:"end_date"`
	TotalTrades       int       `json:"total_trades"`
	WinningTrades     int       `json:"winning_trades"`
	LosingTrades      int       `json:"losing_trades"`
	WinRate           float64   `json:"win_rate" gorm:"type:decimal(5,2)"`
	ProfitLoss        float64   `json:"profit_loss" gorm:"type:decimal(10,2)"`
	ProfitLossPct     float64   `json:"profit_loss_pct" gorm:"type:decimal(10,2)"`
	AverageProfit     float64   `json:"average_profit" gorm:"type:decimal(10,2)"`
	AverageLoss       float64   `json:"average_loss" gorm:"type:decimal(10,2)"`
	MaxDrawdown       float64   `json:"max_drawdown" gorm:"type:decimal(10,2)"`
	MaxDrawdownPct    float64   `json:"max_drawdown_pct" gorm:"type:decimal(5,2)"`
	SharpeRatio       float64   `json:"sharpe_ratio" gorm:"type:decimal(5,2)"`
	SortinoRatio      float64   `json:"sortino_ratio" gorm:"type:decimal(5,2)"`
	AverageHoldingTime float64   `json:"average_holding_time" gorm:"type:decimal(10,2)"` // in hours
	CreatedAt         time.Time `json:"created_at" gorm:"autoCreateTime"`
}
